# -*- coding: utf-8 -*-
"""Aula_26.04.2025_Atividade-01_001.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t47SDcbnqDM1I6Bnq6hDnVkP_lh4V7sX

#**Faculdade Senac Pernambuco**
###MBA em Ciência de Dados e Inteligência Artificial - Turma: 2025
###Criação de um Data Storytelling com Streamlit
Petrônio João da Silva

________________________________________________________________________________
________________________________________________________________________________

##Importação de Bibliotecas
"""
import streamlit as st
# NUMPY - funções essencias para álgebra linear, manipulação de imagens e cálculos de arrays
import numpy as np

# PANDAS - possibilita preparação e operação de dados em alta performance. Trabalha com duas estruturas principais: Series (Array unidimensional) e Dataframes (bidimensional)
import pandas as pd

# MATPLOTLIB - fornece visualização de dados
import matplotlib.pyplot as plt

# SEABORN - melhora a aparência dos gráficos do matplotlib
import seaborn as sb

# SCIKIT-LEARN - utilização de Machine Learning, contendo uma variedade de algoritmos eficientes para inteligência artificial e modelagem estatística
import sklearn as skl


#from google.colab import drive

# Montar o Google Drive
#drive.mount('/content/drive')

# A variável "url" guarda do endereço do local onde os dados estão disponíveis
url = 'machinery_data.csv'

# Criação do DataFrame a partir da leitura (importação) dos dados
df = pd.read_csv(url, sep=',')
st.write('Olá')
# Exibição inicial dos dados
df.head()

df['Machine_Type'].value_counts()



df.info()

df.describe()

manutencao = df.groupby(['Maintenance_Date']).agg(maquina = ('Machine_Type','sum'), falhas = ('Failures','sum'))

plt.figure(figsize=(8, 6))
plt.bar(manutencao.maquina, manutencao.falhas, color='red')
plt.title('Falhas por Máquina')
plt.xlabel('Máquina')
plt.ylabel('N° de Falhas')
plt.show()
